spring:
  datasource:
    url: jdbc:mariadb://fmcsa-historical-aurora.cluster-cryibycdtabf.us-east-1.rds.amazonaws.com/ffdevmdb
    username: root
    password: Fri3ndLyDevs
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
